### ISSUE TITLE
[superapix] Galaxie ne se met pas à jour

### ISSUE THREAD

**Issue by Beben41** [OGSteam/mod-oversight#8]
Hello, 

Lors de la MàJ/Exécution du mod superapix, la sous-rubrique Galaxie ne se met pas à jour (contrairement aux autres sous-rubriques). 
Elle est bloquée (à ce jour) au 30/11. Pas de message d'erreur apparent. 

Merci, 
Benoit

**Comment by machine62** [comment]
mauvais mod
