### ISSUE TITLE
la desinstallation impossible

### ISSUE THREAD

**Issue by olivierfasquelle** [OGSteam/mod-oversight#9]

**Comment by machine62** [comment]
Erreur a la desinstallation reproduite 
"Array to string conversion"

Impact en fait ogspy ...

sur uninstall_mod
$mod_uninstall_table = array(TABLE_OVERSIGHT,TABLE_OVERSIGHT_PLAYERS);
uninstall_mod($mod_uninstall_name, $mod_uninstall_table);

la fonction function uninstall_mod n'accepte pas les array() alors que  $Mod_Model->drop_custum_table($mod_uninstall_table) oui 
voir pour corriger   
ligne journalisation
"log_("debug", "DROP TABLE IF EXISTS " . $mod_uninstall_table);"

**Comment by machine62** [comment]
corrigé avec 
 https://github.com/OGSteam/mod-oversight/releases/tag/0.2.0
et ogspy
3.3.9
